### ISSUE TITLE
change order after changing in categories or articles order

### ISSUE THREAD

**Issue by crossplatformcode** [gruz/MenuAry#2]
After change order of a category or article in content, in menu no action happens for reorder menu based on order of contents. 
Please check this issue.
Thanks.

**Comment by gruz** [comment]
I'm afraid nothing is possible here if you don't save the article. There is no system event fired like onContentReorder. So it's not possible to catch the reorder moment. It's possible to catch the publish moment, as there is onContentChangeState event. 

The only idea I have is very heavy for the Joomla itself. It's to store `lft/rgt`(categories) or `ordering` (articles) values of tracked by MenuAry items somewhere and on every page load check is the tracked items' lft/rgt/ordering values are changed. It should be an additional SQL query on every page load. 

Why on every, but not only at  articles view or categories view. Imagine you have loaded the articles list page. The ordering values are not changed yet. Then you reorder articles, the values are changed but the page is not reloaded (the order is changed via Ajax). So the plugin has no potential opportunity to be run. So you leave the page - plugin was not loaded after the order was changed at the articles view
because if you reorder articles you don't need to visit the articles list page again. 

Any ideas, thoughts?

**Comment by gruz** [comment]
An idea for myself
There is no event like onSaveOrderAjax, but there metods in several contollers. I need com_content and com_category.
Use MVC Override plugin approach in MenuAry to override the conroller methods to trigger MenuAry plugin from the controllers.

**Comment by gruz** [comment]
Please check the latest version http://gruz.org.ua/en/extensions/menuary-automatic-menu.html
Should work.
